# Generated by Django 4.2.4 on 2023-08-06 15:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='img',
            field=models.ImageField(default='https://www.shareicon.net/data/2016/07/05/791224_man_512x512.png', upload_to='pics'),
        ),
        migrations.AddField(
            model_name='user',
            name='player_ability',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0, verbose_name='Ability'),
        ),
        migrations.AddField(
            model_name='user',
            name='player_district',
            field=models.CharField(choices=[('tvm', 'Thiruvananthapuram'), ('klm', 'Kollam'), ('ptmta', 'Pathanamthitta'), ('alp', 'Alappuzha'), ('ktm', 'Kottayam'), ('idk', 'Idukki'), ('ern', 'Ernakulam'), ('thr', 'Thrissur'), ('plk', 'Palakkad'), ('mlp', 'Malappuram'), ('kzkd', 'Kozhikkod'), ('wnd', 'Wayanad'), ('knr', 'Kannur'), ('ksrkd', 'Kasaragod')], default='', max_length=20, verbose_name='District'),
        ),
        migrations.AddField(
            model_name='user',
            name='player_dob',
            field=models.DateField(default=datetime.date.today, verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='user',
            name='player_foot',
            field=models.CharField(choices=[('left', 'Left'), ('right', 'Right'), ('both', 'Both')], default='', max_length=10, verbose_name='Prefered Foot'),
        ),
        migrations.AddField(
            model_name='user',
            name='player_locality',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Locality'),
        ),
        migrations.AddField(
            model_name='user',
            name='player_pos',
            field=models.CharField(choices=[('gk', 'GoalKeeper'), ('lb', 'Left Back'), ('rb', 'Right Back'), ('cb', 'Centre Back'), ('cdm', 'Centre Defensive Midfielder'), ('cm', 'Centre Midfielder'), ('cam', 'Centre Attackin Midfielder'), ('lm', 'Left Midfileder'), ('rm', 'Right Midfielder'), ('lw', 'Left Winger'), ('rw', 'Right Winger'), ('st', 'Striker')], default='', max_length=30, verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='user',
            name='player_potential',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0, verbose_name='Potential'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
