# Generated by Django 4.2.4 on 2023-08-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='player_district',
            field=models.CharField(choices=[('Thiruvananthapuram', 'Thiruvananthapuram'), ('Kollam', 'Kollam'), ('Pathanamthitta', 'Pathanamthitta'), ('Alappuzha', 'Alappuzha'), ('Kottayam', 'Kottayam'), ('Idukki', 'Idukki'), ('Ernakulam', 'Ernakulam'), ('Thrissur', 'Thrissur'), ('Palakkad', 'Palakkad'), ('Malappuram', 'Malappuram'), ('Kozhikkod', 'Kozhikkod'), ('Wayanad', 'Wayanad'), ('Kannur', 'Kannur'), ('Kasaragod', 'Kasaragod')], default='', max_length=20, verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='user',
            name='player_foot',
            field=models.CharField(choices=[('Left', 'Left'), ('Right', 'Right'), ('Both', 'Both')], default='', max_length=10, verbose_name='Prefered Foot'),
        ),
        migrations.AlterField(
            model_name='user',
            name='player_pos',
            field=models.CharField(choices=[('GoalKeeper', 'GoalKeeper'), ('Left Back', 'Left Back'), ('Right Back', 'Right Back'), ('Centre Back', 'Centre Back'), ('Centre Defensive Midfielder', 'Centre Defensive Midfielder'), ('cm', 'Centre Midfielder'), ('Centre Attackin Midfielder', 'Centre Attackin Midfielder'), ('Left Midfileder', 'Left Midfileder'), ('Right Midfielder', 'Right Midfielder'), ('Left Winger', 'Left Winger'), ('Right Winger', 'Right Winger'), ('Striker', 'Striker')], default='', max_length=30, verbose_name='Position'),
        ),
    ]
