# Generated by Django 4.2.4 on 2023-08-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_player_district_alter_user_player_foot_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='player_district',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='player_locality',
            new_name='locality',
        ),
        migrations.AddField(
            model_name='user',
            name='club_reputation',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0, verbose_name='Club Reputation'),
        ),
        migrations.AddField(
            model_name='user',
            name='desc',
            field=models.CharField(default='', max_length=100, verbose_name='Description'),
        ),
    ]
