# Generated by Django 4.2.4 on 2023-08-07 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_rename_player_district_user_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='club_name',
            field=models.CharField(default='', max_length=30, verbose_name='Club Name'),
        ),
    ]
