# Generated by Django 4.2.4 on 2023-08-18 04:03

import account.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_user_club_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('player_dob', models.DateField(default=datetime.date.today, validators=[account.models.validate_dob], verbose_name='Date of Birth')),
                ('player_pos', models.CharField(choices=[('GoalKeeper', 'GoalKeeper'), ('Left Back', 'Left Back'), ('Right Back', 'Right Back'), ('Centre Back', 'Centre Back'), ('Centre Defensive Midfielder', 'Centre Defensive Midfielder'), ('cm', 'Centre Midfielder'), ('Centre Attackin Midfielder', 'Centre Attackin Midfielder'), ('Left Midfileder', 'Left Midfileder'), ('Right Midfielder', 'Right Midfielder'), ('Left Winger', 'Left Winger'), ('Right Winger', 'Right Winger'), ('Striker', 'Striker')], default='', max_length=30, verbose_name='Position')),
                ('district', models.CharField(choices=[('Thiruvananthapuram', 'Thiruvananthapuram'), ('Kollam', 'Kollam'), ('Pathanamthitta', 'Pathanamthitta'), ('Alappuzha', 'Alappuzha'), ('Kottayam', 'Kottayam'), ('Idukki', 'Idukki'), ('Ernakulam', 'Ernakulam'), ('Thrissur', 'Thrissur'), ('Palakkad', 'Palakkad'), ('Malappuram', 'Malappuram'), ('Kozhikkod', 'Kozhikkod'), ('Wayanad', 'Wayanad'), ('Kannur', 'Kannur'), ('Kasaragod', 'Kasaragod')], default='', max_length=20, verbose_name='District')),
                ('locality', models.CharField(blank=True, default='', max_length=50, verbose_name='Locality')),
                ('player_foot', models.CharField(choices=[('Left', 'Left'), ('Right', 'Right'), ('Both', 'Both')], default='', max_length=10, verbose_name='Prefered Foot')),
                ('player_ability', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0, verbose_name='Ability')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='player_dob',
            field=models.DateField(default=datetime.date.today, validators=[account.models.validate_dob], verbose_name='Date of Birth'),
        ),
    ]
