# Generated by Django 4.2.4 on 2023-08-27 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_user_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestedClubs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interested_clubs_as_club', to=settings.AUTH_USER_MODEL)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interested_clubs_as_player', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
