# Generated by Django 4.2.4 on 2023-08-27 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_interestedclubs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InterestedClubs',
        ),
    ]
