# Generated by Django 4.2.4 on 2023-08-27 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_interestedclubs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interestedclubs',
            old_name='club_id',
            new_name='club',
        ),
        migrations.RenameField(
            model_name='interestedclubs',
            old_name='player_id',
            new_name='player',
        ),
    ]
