# Generated by Django 4.2.4 on 2023-08-27 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_rename_club_id_interestedclubs_club_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortlistedPlayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortlisted_players_as_club', to=settings.AUTH_USER_MODEL)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortlisted_players_as_player', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
