# Generated by Django 4.2.4 on 2023-08-30 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_rename_player_shortlistedclubscouts_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='scouted_by',
            field=models.CharField(default='', max_length=30),
        ),
    ]
