# Generated by Django 4.2.4 on 2023-08-31 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='club_negotiating',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='player_negotiating',
            field=models.BooleanField(default=False),
        ),
    ]
