# Generated by Django 4.2.4 on 2023-09-01 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_contract_club_negotiating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='club_negotiating',
            new_name='contractAccepted',
        ),
    ]
