# Generated by Django 4.2.4 on 2023-09-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_newfeeds'),
    ]

    operations = [
        migrations.AddField(
            model_name='newfeeds',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
