# Generated by Django 4.2.4 on 2023-09-06 04:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_newfeeds_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newfeeds',
            name='likes',
        ),
        migrations.CreateModel(
            name='likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.newfeeds')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_as_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
