# Generated by Django 4.2.4 on 2023-09-06 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_remove_newfeeds_likes_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likes',
            old_name='feed_id',
            new_name='feed',
        ),
    ]
