# Generated by Django 4.2.4 on 2023-09-20 03:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0031_following'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('followed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_followed', to=settings.AUTH_USER_MODEL)),
                ('followingg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_followingg', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
