# Generated by Django 4.2.4 on 2023-10-05 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0037_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_pos',
            field=models.CharField(choices=[('GK', 'GoalKeeper'), ('LB', 'Left Back'), ('RB', 'Right Back'), ('CB', 'Centre Back'), ('CDM', 'Centre Defensive Midfielder'), ('CM', 'Centre Midfielder'), ('CAM', 'Centre Attackin Midfielder'), ('LM', 'Left Midfileder'), ('RM', 'Right Midfielder'), ('LM', 'Left Winger'), ('RW', 'Right Winger'), ('ST', 'Striker')], default='', max_length=30, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='user',
            name='player_pos',
            field=models.CharField(choices=[('GK', 'GoalKeeper'), ('LB', 'Left Back'), ('RB', 'Right Back'), ('CB', 'Centre Back'), ('CDM', 'Centre Defensive Midfielder'), ('CM', 'Centre Midfielder'), ('CAM', 'Centre Attackin Midfielder'), ('LM', 'Left Midfileder'), ('RM', 'Right Midfielder'), ('LM', 'Left Winger'), ('RW', 'Right Winger'), ('ST', 'Striker')], default='', max_length=30, verbose_name='Position'),
        ),
    ]
