# Generated by Django 4.2.4 on 2023-10-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0038_alter_player_player_pos_alter_user_player_pos'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='first',
            field=models.BooleanField(default=True),
        ),
    ]
