# Generated by Django 4.2.4 on 2023-10-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0039_history_first'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='first',
            field=models.BooleanField(default=False),
        ),
    ]
