# Generated by Django 4.2.4 on 2023-10-08 12:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0040_alter_history_first'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits without spaces or special characters.', regex='^\\d{10}$')], verbose_name='Phone Number'),
        ),
    ]
