# Generated by Django 4.2.4 on 2024-01-09 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0042_tour'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='tour_date',
            field=models.DateTimeField(null=True),
        ),
    ]
