# Generated by Django 4.2.4 on 2024-01-09 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0043_tour_time_tour_tour_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
