# Generated by Django 4.2.4 on 2024-01-09 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0044_tour_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='district',
            field=models.CharField(choices=[('Thiruvananthapuram', 'Thiruvananthapuram'), ('Kollam', 'Kollam'), ('Pathanamthitta', 'Pathanamthitta'), ('Alappuzha', 'Alappuzha'), ('Kottayam', 'Kottayam'), ('Idukki', 'Idukki'), ('Ernakulam', 'Ernakulam'), ('Thrissur', 'Thrissur'), ('Palakkad', 'Palakkad'), ('Malappuram', 'Malappuram'), ('Kozhikkod', 'Kozhikkod'), ('Wayanad', 'Wayanad'), ('Kannur', 'Kannur'), ('Kasaragod', 'Kasaragod')], max_length=20, null=True, verbose_name='District'),
        ),
        migrations.AddField(
            model_name='tour',
            name='place',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
