# Generated by Django 4.2.4 on 2024-01-18 04:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0045_tour_district_tour_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourEnrole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_join', models.DateTimeField(null=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.tour')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
