# Generated by Django 4.2.4 on 2024-01-30 04:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0049_trials'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrailEnrol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_join', models.DateTimeField(null=True)),
                ('trial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.trials')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
