# Generated by Django 4.2.4 on 2024-02-04 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0050_trailenrol'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
