# Generated by Django 4.2.4 on 2024-02-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0054_trialwinners'),
    ]

    operations = [
        migrations.AddField(
            model_name='trials',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trials',
            name='edited',
            field=models.BooleanField(default=False),
        ),
    ]
