# Generated by Django 4.2.4 on 2024-02-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0055_trials_cancelled_trials_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='score',
            field=models.FloatField(default=0.0),
        ),
    ]
