# Generated by Django 4.2.4 on 2024-03-06 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0058_playerstats_goalkeepingstats'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoutPlayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ability', models.IntegerField()),
                ('potential', models.IntegerField()),
                ('position', models.CharField(max_length=50)),
                ('time', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club', to=settings.AUTH_USER_MODEL)),
                ('scout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scout', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
